USE restaurant;

CREATE TABLE Category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)  NOT NULL,
    note VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50)  NOT NULL,
    image VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    quantity int NOT NULL,
    cost DECIMAL(12, 0) NOT NULL,
    price DECIMAL(12, 0) NOT NULL,
    categoryId INT,
    FOREIGN KEY (categoryId) REFERENCES Category(id),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50)  NOT NULL,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(100)  NOT NULL,
    role ENUM('ADMIN', 'EMPLOYEE', 'CASHIER') NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(10) NOT NULL UNIQUE,
    isLock TINYINT(1) DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
